version: '3.8'

services:
  service:
    build:
      context: ./app
      dockerfile: ../dockerfile.app
    container_name: user
    ports:
      - '8002:8002'  
    command:
      - python
      - main.py
    env_file: '.\.env'
    restart: always
    networks:
      - default 

networks:
  default:
    external: false