version: '3.8'  # Указывает версию Compose файла

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine  # Указывает образ для контейнера
    hostname: rabbitmq
    container_name: rabbitmq  # Имя контейнера
    # Если .env находиться в тойже дериктории что и docker compose то указывать это явно не требуеться, оно уже подразумеваеться под капотом
    # env_file:
    #   # ХЗ но видимо пороль и логин можно задать через окружение только 1 раз (изменить с guest guest на свой), а деле вероятно нужно их менять через админку, но нужно чтобы в файле окружения были корретыне данные для правильной работы других модулей
    #   - ./.env
    environment:
      # Зачастую чтобы изменения этого файла вступили в силу его недостаточно просто пересобрать `docker compose up --build` нужно сначало его удлалить `docker comopose down -v`, т.к. тома могут хранить в себе старые данные окружения
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}  # Получение данных из окружения
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - '5672:5672'  # Порт для самого rabbitmq
      - '15672:15672'  # Порт для админки
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Монтирование локальной директории в контейнер
    restart: always

# Определение томов
volumes:
  rabbitmq_data:  # Том для хранения данных MySQL