version: '3.8'

services:
  service:
    build:
      context: ./app
      dockerfile: ../dockerfile.app
    container_name: cart
    ports:
      - '8003:8003'  
    command:
      - python
      - main.py
    env_file: '.\.env'
    restart: always
    networks:
      - default 

networks:
  default:
    external: false