from enum import Enum


class Emoji(Enum):
    INDENT = ""
    SAVE = ""
    FILES = ""
    BOOKS = ""
    BOOK = ""
    SEARCH = ""
    INTERNET = ""
    GAME = ""
    ARROW_LEFT = ""
    ARROW_RIGHT = ""
    ARROW_UP = ""
    ARROW_DOWN = ""
    ARROW_RELOAD  = ""
    CAR = ""
    VACATION = ""
    BULB = ""
    MUSEUM = ""
    GEARS = ""
    WATCH = ""
    SAND_WATCH = ""
    EYE = ""
    EYES = ""
    CALENDAR = ""
    ERR = ""
    CROSS = ""
    MARK_GREEN = ""
    MARK_BLUE = ""
    SUCCESS = ""
    EXCLAIM = ""
    QUASTION = ""
    AUTH = ""
    WELCOME = ""
    HEART = ""
    LIKE = ""
    NOTEBOOK = ""
    ADMIN = ""
    ADMIN_MODE = ""
    LOCK = ""
    LAPTOP = ""
    RATE = ""
    ADD_NEW = ""
    STAR = ""
    RULES = ""
    BASKET = ""
    DISPOSAL = ""
    STOP = ""
    STOP_1 = ""
    TONGUE = ""
    BRAIN = ""
    MESSAGE = ""
    LINK = ""
    SCHEME = ""
    CAMERA = ""

    def __str__(self):
        return f'{self.value}{Emoji.INDENT.value}'