version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: user_db
    env_file: '.\.env'
    ports:
      - '5433:5432' 
    networks:
      - default    
    volumes:
      - user_db:/var/lib/postgresql/data
    restart: always

volumes:
  user_db: {}

networks:
  default:
    external: false